---
# main playbook
- hosts: storage
  gather_facts: no
  become: true
  roles:
    - network_facts
    - nfs_server

- hosts: targets[0]
  gather_facts: no
  become: true
  roles:
    - certs
    - { role: network_facts, tags: ['services', 'deploy'] }
    - datadir
    # - nfs_client
    - docker
    - { role: docker-images, tags: ['images', 'deploy'] }
    - { role: compose-services, tags: ['services', 'deploy'] }