---
# tasks file for roles/docker

# TODO: implement the tasks for Docker installation
- name: Filter required facts
  setup:
    filter:
      - deb_architecture
      - ansible_architecture
      - ansible_distribution_release

- name: Add Docker apt repository key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker apt repository
  apt_repository:
    repo: >
      deb [arch={{ deb_architecture[ansible_architecture] | default('amd64') }}
      signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: true
    state: present

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Check if docker command exists
  ansible.builtin.shell: "command -v docker"
  register: docker_check
  ignore_errors: yes

- name: Assert docker is NOT installed
  ansible.builtin.assert:
    that:
      - docker_check.rc == 0
    fail_msg: "Docker is not installed on this host."